name: flushare
description: "An application to allow sharing between Android and Macos."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Network connections / API's
  permission_handler: ^11.3.1
  file_picker: ^8.1.4
  path_provider: ^2.1.5
  encrypt: ^5.0.3
  flutter_secure_storage: ^4.2.1
  dio: ^5.7.0
  network_info_plus: ^6.1.2
  ping_discover_network_forked: ^0.0.1

  # design and animated
  flutter_animate: ^4.5.0
  fluttertoast: ^8.2.8
  iconsax: ^0.0.8
  linear_timer: ^2.0.0

  # state management and dependecy managers
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  provider: ^6.1.2

  # general/ utilities
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.1"

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/flushare_icon.png"
  min_sdk_android: 21

  macos:
    generate: true
    image_path: "assets/images/flushare_icon.png"

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/static/Rubik-Regular.ttf
